### ISSUE TITLE
`gantry.services.excluded=true` on Nginx Service Not Being Excluded

### ISSUE THREAD

**Issue by pascalandy** [shizunge/gantry#71]
## gantry.yml

I can exclude few services using GANTRY_SERVICES_EXCLUDED. Good :)

```yml
services:
  gantry:
    image: shizunge/gantry:latest
    environment:
      - "GANTRY_NODE_NAME={{.Node.Hostname}}"
      - "GANTRY_SERVICES_EXCLUDED=core_traefik core_autoheal logs_dozzle"
      # The gantry service is able to find the name of itself service. Use GANTRY_SERVICES_SELF when you want to set a different value.
      # - "GANTRY_SERVICES_SELF=${STACK}_gantry"
      - "GANTRY_SLEEP_SECONDS=0"
      - "TZ=America/Toronto"
      - "GANTRY_LOG_LEVEL=DEBUG"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=45 23 0 * * *"
        - "swarm.cronjob.skip-running=true"
...

  scheduler:
    image: crazymax/swarm-cronjob:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
...
```

## nginx

But I would really prefer to exclude some services directly with their respective yml files. Nginx per example.

```yml
services:
  fphosting_web:
    # https://hub.docker.com/_/nginx
    image: nginx:1.27.2-alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello.rule=Host(`fphosting.top`)"
      - "traefik.http.routers.hello.tls=true"
      - "traefik.http.routers.hello.tls.certresolver=myresolver"
      - "traefik.http.routers.hello.entrypoints=websecure"
      - "traefik.http.services.hello.loadbalancer.server.port=80"
      - "autoheal-app=true"
      - "gantry.services.excluded=true"
    networks:
...
```

## logs

When I look at the logs, I see "Skip updating 2003_fphosting_web because the current version is the latest of image nginx:1.27.2-alpine@sha256:..."
So nginx is not excluded.

How should I do this ?

```shell
ntry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:01-05:00][srv650377][INFO] imgupdater_gantry: Starting.
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:02-05:00][srv650377][DEBUG] imgupdater_gantry: Created STATIC_VARIABLES_FOLDER /tmp/tmp.HDCKob
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:02-05:00][srv650377][INFO] imgupdater_gantry: Before updating, Docker Hub rate remains 87.
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:02-05:00][srv650377][DEBUG] imgupdater_gantry: SERVICES_EXCLUDED=core_traefik core_autoheal logs_dozzle
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:02-05:00][srv650377][DEBUG] imgupdater_gantry: SERVICES_EXCLUDED_FILTERS=label=gantry.services.excluded=true
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:03-05:00][srv650377][INFO] imgupdater_gantry: Set GANTRY_SERVICES_SELF to imgupdater_gantry.
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:03-05:00][srv650377][DEBUG] imgupdater_gantry: Exclude service core_autoheal from updating.
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:03-05:00][srv650377][DEBUG] imgupdater_gantry: Exclude service core_traefik from updating.
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:03-05:00][srv650377][DEBUG] imgupdater_gantry: Exclude service logs_dozzle from updating.
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:03-05:00][srv650377][INFO] imgupdater_gantry: Starting updating.
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:03-05:00][srv650377][INFO] imgupdater_gantry: Inspecting 3 service(s).
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:04-05:00][srv650377][DEBUG] imgupdater_gantry: Skip updating imgupdater_gantry because the current version is the latest of image shizunge/gantry:latest@sha256:8c8d30fce90248929e083422debf076d9dd18fc23c71575be255967d34b6d573.
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:04-05:00][srv650377][DEBUG] imgupdater_gantry: Run 1 _inspect_service in parallel.
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:05-05:00][srv650377][DEBUG] imgupdater_gantry worker0: Skip updating 2003_fphosting_web because the current version is the latest of image nginx:1.27.2-alpine@sha256:74175cf34632e88c6cfe206897cbfe2d2fecf9bf033c40e7f9775a3689e8adc7.
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:06-05:00][srv650377][DEBUG] imgupdater_gantry worker0: Skip updating 2004_firepresshosting_gst because the current version is the latest of image devmtl/ghostfire:stable@sha256:45feb615db17334f799bfe30c6edce5ef47dcc2e99d0d7f8b63cf77d1e7c9708.
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:06-05:00][srv650377][INFO] imgupdater_gantry: No new images for 3 service(s):
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:06-05:00][srv650377][INFO] imgupdater_gantry: - 2003_fphosting_web
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:06-05:00][srv650377][INFO] imgupdater_gantry: - 2004_firepresshosting_gst
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:06-05:00][srv650377][INFO] imgupdater_gantry: - imgupdater_gantry
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:06-05:00][srv650377][DEBUG] imgupdater_gantry: Run 1 _update_single_service in parallel.
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:06-05:00][srv650377][INFO] imgupdater_gantry: After updating, Docker Hub rate remains 86. Used rate 1.
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:06-05:00][srv650377][INFO] imgupdater_gantry: No images to remove.
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:06-05:00][srv650377][INFO] imgupdater_gantry: No services updated.
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:06-05:00][srv650377][DEBUG] imgupdater_gantry notify: Skip sending notification via Apprise.
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:06-05:00][srv650377][DEBUG] imgupdater_gantry: Removing STATIC_VARIABLES_FOLDER /tmp/tmp.HDCKob
imgupdater_gantry.1.1qys9kb0scd4@srv650377    | [2024-11-27T12:25:06-05:00][srv650377][INFO] imgupdater_gantry: Done. Use 0m 5s. 0 error(s).
```

## docker ps

```shell
mrandy@srv650377:~/fphosting$ docker ps --format "table {{.Image}}\t{{.Status}}\t{{.Names}}"
IMAGE                           STATUS                       NAMES
crazymax/swarm-cronjob:latest   Up 3 minutes                 cron_scheduler.1.fm2bt7zbdj55bxm85rb2uekwl
nginx:1.27.2-alpine             Up 3 minutes (healthy)       2003_fphosting_web.1.u6zx0364pejd2ppec6tacrkui
amir20/dozzle:v8.8.2            Up 24 minutes (healthy)      logs_dozzle.1.gcxnpsgvzqzbz3oxea6fg29md
willfarrell/autoheal:1.2.0      Up 24 minutes (healthy)      core_autoheal.1.yxozt5x742xcjz2ctp2spkycn
devmtl/ghostfire:stable         Up About an hour (healthy)   2004_firepresshosting_gst.1.jc7ftq48iwcq71n1h2j5mwwbh
traefik:v3.2.1                  Up 2 hours (healthy)         core_traefik.1.i8spy48j2llpslwonwz50xrz9
```

Thank you!

**Comment by shizunge** [comment]
You need to set the label on the service rather than the container.

```
services:
  fphosting_web:
    image: nginx:1.27.2-alpine
    labels:
      - your_container_label
    networks:
    deploy:
      labels:
        - your_service_label
...
```

**Comment by pascalandy** [comment]
works thank you!!

```shell
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:46-05:00] Loading libraries from .
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:46-05:00][srv650377][DEBUG] Created STATIC_VARIABLES_FOLDER /tmp/tmp.cDiJpL
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:47-05:00][srv650377][INFO] imgupdater_gantry: Run on Docker host srv650377. Docker version client 26.1.5 (API 1.45) server 27.3.1 (API 1.47)
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:47-05:00][srv650377][INFO] imgupdater_gantry: Starting.
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:47-05:00][srv650377][DEBUG] imgupdater_gantry: Created STATIC_VARIABLES_FOLDER /tmp/tmp.NIoiHn
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:47-05:00][srv650377][INFO] imgupdater_gantry: Before updating, Docker Hub rate remains 86.
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:47-05:00][srv650377][DEBUG] imgupdater_gantry: SERVICES_EXCLUDED=core_traefik core_autoheal logs_dozzle
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:47-05:00][srv650377][DEBUG] imgupdater_gantry: SERVICES_EXCLUDED_FILTERS=label=gantry.services.excluded=true
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:47-05:00][srv650377][DEBUG] imgupdater_gantry: Exclude service 2003_fphosting_web from updating.
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:48-05:00][srv650377][INFO] imgupdater_gantry: Set GANTRY_SERVICES_SELF to imgupdater_gantry.
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:48-05:00][srv650377][DEBUG] imgupdater_gantry: Exclude service core_autoheal from updating.
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:48-05:00][srv650377][DEBUG] imgupdater_gantry: Exclude service core_traefik from updating.
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:48-05:00][srv650377][DEBUG] imgupdater_gantry: Exclude service logs_dozzle from updating.
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:48-05:00][srv650377][INFO] imgupdater_gantry: Starting updating.
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:48-05:00][srv650377][INFO] imgupdater_gantry: Inspecting 2 service(s).
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:49-05:00][srv650377][DEBUG] imgupdater_gantry: Skip updating imgupdater_gantry because the current version is the latest of image shizunge/gantry:latest@sha256:8c8d30fce90248929e083422debf076d9dd18fc23c71575be255967d34b6d573.
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:49-05:00][srv650377][DEBUG] imgupdater_gantry: Run 1 _inspect_service in parallel.
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:50-05:00][srv650377][DEBUG] imgupdater_gantry worker0: Skip updating 2004_firepresshosting_gst because the current version is the latest of image devmtl/ghostfire:stable@sha256:45feb615db17334f799bfe30c6edce5ef47dcc2e99d0d7f8b63cf77d1e7c9708.
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:50-05:00][srv650377][INFO] imgupdater_gantry: No new images for 2 service(s):
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:50-05:00][srv650377][INFO] imgupdater_gantry: - 2004_firepresshosting_gst
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:50-05:00][srv650377][INFO] imgupdater_gantry: - imgupdater_gantry
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:50-05:00][srv650377][DEBUG] imgupdater_gantry: Run 1 _update_single_service in parallel.
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:50-05:00][srv650377][INFO] imgupdater_gantry: After updating, Docker Hub rate remains 85. Used rate 1.
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:50-05:00][srv650377][INFO] imgupdater_gantry: No images to remove.
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:50-05:00][srv650377][INFO] imgupdater_gantry: No services updated.
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:50-05:00][srv650377][DEBUG] imgupdater_gantry notify: Skip sending notification via Apprise.
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:50-05:00][srv650377][DEBUG] imgupdater_gantry: Removing STATIC_VARIABLES_FOLDER /tmp/tmp.NIoiHn
imgupdater_gantry.1.036uivzd5blq@srv650377    | [2024-11-27T13:15:50-05:00][srv650377][INFO] imgupdater_gantry: Done. Use 0m 3s. 0 error(s).
```

## solution

```yml
services:
  fphosting_web:
    # https://hub.docker.com/_/nginx
    image: nginx:1.27.2-alpine
    # container labels
    labels:
      - "traefik.enable=true"
...
    networks:
      - ...
    volumes:
...
    deploy:
      # service labels
      labels:
        - "gantry.services.excluded=true"
      update_config:
        order: start-first
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
```
