### ISSUE TITLE
Is there a way to do an healthcheck on the service?

### ISSUE THREAD

**Issue by pascalandy** [shizunge/gantry#72]
Is there a way to do an healthcheck on the service

Something like this:

```yml
services:
  gantry:
    image: shizunge/gantry:latest
    environment:
      - "GANTRY_NODE_NAME={{.Node.Hostname}}"
      - "GANTRY_SERVICES_EXCLUDED=core_traefik core_autoheal logs_dozzle"
      - "GANTRY_SLEEP_SECONDS=0"
      - "TZ=America/Toronto"
      - "GANTRY_LOG_LEVEL=DEBUG"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=45 23 0 * * *"
        - "swarm.cronjob.skip-running=true"
      update_config:
        order: start-first
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
```
